# Generated by Django 6.0.7 on 2026-07-21 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='stations.station'),
        ),
    ]
