# Generated by Django 6.0.7 on 2026-07-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Mã cấu hình')),
                ('value', models.CharField(max_length=500, verbose_name='Giá trị')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
