# Generated by Django 6.0.7 on 2026-07-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systemconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='auth_header',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Token/Header xác thực'),
        ),
    ]
