# Generated by Django 6.0.7 on 2026-07-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemconfig_auth_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='auto_sync_enabled',
            field=models.BooleanField(default=False, verbose_name='Tự động đồng bộ'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='last_sync_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Trạng thái đồng bộ cuối'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='last_sync_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lần đồng bộ cuối'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='sync_interval_minutes',
            field=models.IntegerField(default=1440, verbose_name='Chu kỳ đồng bộ (phút)'),
        ),
    ]
