# Generated by Django 6.0.7 on 2026-07-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_systemconfig_auto_sync_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='sync_count',
            field=models.IntegerField(default=0, verbose_name='Số lần đồng bộ'),
        ),
    ]
