# Generated by Django 6.0.7 on 2026-07-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_systemconfig_sync_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='is_syncing',
            field=models.BooleanField(default=False, verbose_name='Đang đồng bộ'),
        ),
    ]
