# Generated by Django 6.0.7 on 2026-07-18 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_code', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('ASSIGNED_TO_SC', 'Assigned to SC'), ('RECEIVED', 'Received'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=50)),
                ('scan_file', models.FileField(upload_to='scans/')),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.relay')),
            ],
        ),
        migrations.CreateModel(
            name='SignatureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('signature_hash', models.CharField(max_length=256)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='sheets.settingsheet')),
            ],
        ),
    ]
