# Generated by Django 6.0.7 on 2026-07-18 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settingsheet',
            options={'permissions': [('can_view_stations', 'Can view stations'), ('can_manage_users', 'Can manage users & roles'), ('can_create_sheet', 'Can create sheet and run OCR'), ('can_approve_sheet', 'Can review and approve sheet'), ('can_dispatch_sheet', 'Can dispatch sheet to technician'), ('can_execute_sheet', 'Can execute sheet and sign (Technician)'), ('can_supervise_sheet', 'Can supervise sheet and sign (Supervisor)')]},
        ),
    ]
