# Generated by Django 6.0.7 on 2026-07-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_alter_settingsheet_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsheet',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued (A0/A1 Signed)'), ('REVIEWED', 'Reviewed'), ('TRANSFERRED', 'Transferred to Technician'), ('RECEIVED', 'Received by Technician'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=50),
        ),
    ]
