# Generated by Django 6.0.7 on 2026-07-18 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0004_alter_settingsheet_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsheet',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settingsheet',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sheets', to=settings.AUTH_USER_MODEL),
        ),
    ]
