# Generated by Django 6.0.7 on 2026-07-18 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0005_settingsheet_assigned_to_settingsheet_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsheet',
            name='assigned_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sup_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settingsheet',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_sheets', to=settings.AUTH_USER_MODEL),
        ),
    ]
