# Generated by Django 6.0.7 on 2026-07-19 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0006_settingsheet_assigned_supervisor_and_more'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingsheet',
            name='assigned_supervisor',
        ),
        migrations.RemoveField(
            model_name='settingsheet',
            name='assigned_technician',
        ),
        migrations.AddField(
            model_name='settingsheet',
            name='relay_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='settingsheet',
            name='relay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.relay'),
        ),
        migrations.AlterField(
            model_name='settingsheet',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
