# Generated by Django 6.0.7 on 2026-07-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0007_remove_settingsheet_assigned_supervisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsheet',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued (Ready for Dispatch)'), ('TRANSFERRED', 'Transferred to Technician'), ('RECEIVED', 'Received by Technician'), ('PENDING_REVIEW', 'Pending Operation Approval'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=50),
        ),
    ]
