# Generated by Django 6.0.7 on 2026-07-20 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0009_settingsheet_supervisor_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsheet',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settingsheet',
            name='revert_to_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revert_from_sheets', to='sheets.settingsheet'),
        ),
        migrations.AddField(
            model_name='settingsheet',
            name='reverted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settingsheet',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
