# Generated by Django 6.0.7 on 2026-07-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0010_settingsheet_is_temporary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settingsheet',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_stations', 'Can view stations'), ('can_view_checks', 'Can view periodic checks'), ('can_manage_users', 'Can manage users & roles'), ('can_create_sheet', 'Can create sheet and run OCR'), ('can_approve_sheet', 'Can review and approve sheet'), ('can_dispatch_sheet', 'Can dispatch sheet to technician'), ('can_execute_sheet', 'Can execute sheet and sign (Technician)'), ('can_supervise_sheet', 'Can supervise sheet and sign (Supervisor)')]},
        ),
        migrations.AlterField(
            model_name='settingsheet',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued (Ready for Dispatch)'), ('ROUTED_TO_STATION', 'Routed to Station'), ('TRANSFERRED', 'Transferred to Technician'), ('RECEIVED', 'Received by Technician'), ('PENDING_REVIEW', 'Pending Operation Approval'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=50),
        ),
    ]
