# Generated by Django 6.0.7 on 2026-07-21 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0011_alter_settingsheet_options_alter_settingsheet_status'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsheet',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.station'),
        ),
    ]
