# Generated by Django 6.0.7 on 2026-07-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0012_settingsheet_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsheet',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settingsheet',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued (Ready for Dispatch)'), ('ROUTED_TO_STATION', 'Routed to Station'), ('TRANSFERRED', 'Transferred to Technician'), ('RECEIVED', 'Received by Technician'), ('PENDING_ADMIN_APPROVAL', 'Pending Admin Approval'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=50),
        ),
    ]
