# Generated by Django 6.0.7 on 2026-07-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0013_settingsheet_assigned_at_alter_settingsheet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsheet',
            name='edit_logs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='settingsheet',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('ISSUED', 'Chờ Rà soát'), ('ROUTED_TO_STATION', 'Đã chuyển về Trạm'), ('TRANSFERRED', 'Đã giao KTV'), ('RECEIVED', 'Đang thực hiện'), ('PENDING_ADMIN_APPROVAL', 'Chờ Duyệt Ban hành'), ('COMPLETED', 'Hoàn thành')], default='DRAFT', max_length=50),
        ),
    ]
