# Generated by Django 6.0.7 on 2026-07-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0014_settingsheet_edit_logs_alter_settingsheet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsheet',
            name='has_parameters_changed',
            field=models.BooleanField(default=False),
        ),
    ]
