# Generated by Django 6.0.7 on 2026-07-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0015_settingsheet_has_parameters_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsheet',
            name='scan_file',
            field=models.FileField(blank=True, null=True, upload_to='scans/'),
        ),
    ]
