# Generated by Django 6.0.7 on 2026-07-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0016_alter_settingsheet_scan_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsheet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
