# Generated by Django 6.0.7 on 2026-08-01 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0017_settingsheet_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcrJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_id', models.CharField(help_text='ID duy nhất để giao tiếp với hệ thống OCR', max_length=128, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('PROCESSING', 'Đang xử lý'), ('SUCCESS', 'Thành công'), ('SUCCESS_WITH_WARNINGS', 'Thành công (có cảnh báo)'), ('FAILED', 'Thất bại')], default='PENDING', max_length=50)),
                ('review_status', models.CharField(blank=True, max_length=50, null=True)),
                ('result_data', models.JSONField(blank=True, help_text='Toàn bộ JSON trả về từ OCR', null=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('error_stage', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_jobs', to='sheets.settingsheet')),
            ],
        ),
    ]
