# Generated by Django on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0018_ocrjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrjob',
            name='error_detail',
            field=models.TextField(blank=True, help_text='Chi tiết nguyên nhân lỗi OCR', null=True),
        ),
    ]
