# Generated by Django 6.0.7 on 2026-08-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0019_ocrjob_error_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrjob',
            name='device_mode',
            field=models.CharField(choices=[('CPU', 'CPU'), ('GPU', 'GPU (CUDA)')], default='CPU', help_text='Chế độ phần cứng xử lý (CPU/GPU)', max_length=10),
        ),
    ]
