# Generated by Django 6.0.7 on 2026-07-18 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bay_code', models.CharField(max_length=50)),
                ('bay_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(max_length=50, unique=True)),
                ('station_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relay_code', models.CharField(max_length=50)),
                ('relay_name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('bay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relays', to='stations.bay')),
            ],
        ),
        migrations.CreateModel(
            name='RelaySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_code', models.CharField(max_length=50)),
                ('parameter_name', models.CharField(max_length=100)),
                ('standard_value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('tolerance_min', models.FloatField()),
                ('tolerance_max', models.FloatField()),
                ('relay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='stations.relay')),
            ],
        ),
        migrations.AddField(
            model_name='bay',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bays', to='stations.station'),
        ),
    ]
