# Generated by Django 6.0.7 on 2026-07-23 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayAutoCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('MATCH', 'Trùng khớp'), ('MISMATCH', 'Có sai lệch'), ('API_ERROR', 'Lỗi kết nối API')], default='MATCH', max_length=20)),
                ('api_raw_data', models.JSONField(blank=True, null=True)),
                ('differences', models.JSONField(blank=True, null=True)),
                ('relay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_checks', to='stations.relay')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
