# Generated by Django 6.0.7 on 2026-07-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_relayautochecklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='relay',
            name='auto_check_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relay',
            name='check_interval_unit',
            field=models.CharField(choices=[('s', 'Giây'), ('m', 'Phút'), ('h', 'Giờ'), ('d', 'Ngày'), ('M', 'Tháng'), ('y', 'Năm')], default='h', max_length=1),
        ),
        migrations.AddField(
            model_name='relay',
            name='check_interval_value',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='relay',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relay',
            name='next_check_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
