# Generated by Django 6.0.7 on 2026-07-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_relay_auto_check_enabled_relay_check_interval_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relay',
            name='check_interval_unit',
            field=models.CharField(choices=[('s', 'Giây'), ('m', 'Phút'), ('h', 'Giờ'), ('d', 'Ngày'), ('M', 'Tháng'), ('y', 'Năm'), ('e', 'Cụ thể (1 lần)')], default='h', max_length=1),
        ),
    ]
