# Generated by Django 6.0.7 on 2026-07-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_alter_relay_check_interval_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relay',
            name='auto_check_enabled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='relay',
            name='next_check_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
