# Generated by Django 6.0.7 on 2026-07-23 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_alter_relay_auto_check_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relay',
            name='is_paused_for_correction',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='relay',
            name='paused_schedule_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CorrectionTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DISPATCHER', 'Phân phối viên xử lý'), ('STATION', 'Trạm xử lý'), ('TECH', 'Kỹ thuật viên xử lý'), ('SUPERVISOR', 'Giám sát ký'), ('ADMIN', 'Admin ký duyệt'), ('RESOLVED', 'Hoàn tất')], default='DISPATCHER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.relayautochecklog')),
                ('relay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_tickets', to='stations.relay')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('signature_hash', models.CharField(max_length=256)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='stations.correctionticket')),
            ],
            options={
                'ordering': ['signed_at'],
            },
        ),
    ]
