# Generated by Django 6.0.7 on 2026-07-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_relay_is_paused_for_correction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'verbose_name': 'Danh mục Trạm', 'verbose_name_plural': 'Danh mục Trạm'},
        ),
        migrations.AddField(
            model_name='station',
            name='id_capda',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Cấp điện áp (ID_CAPDA)'),
        ),
        migrations.AddField(
            model_name='station',
            name='id_dvi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Đơn vị (ID_DVI)'),
        ),
        migrations.AddField(
            model_name='station',
            name='id_kieu_ht_dk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Kiểu HT ĐK (ID_KIEU_HT_DK)'),
        ),
        migrations.AddField(
            model_name='station',
            name='id_kieu_tram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Kiểu trạm (ID_KIEU_TRAM)'),
        ),
        migrations.AddField(
            model_name='station',
            name='id_loai_tram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Loại trạm (ID_LOAI_TRAM)'),
        ),
        migrations.AddField(
            model_name='station',
            name='id_phuong',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Phường (ID_PHUONG)'),
        ),
        migrations.AddField(
            model_name='station',
            name='id_quan',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Quận (ID_QUAN)'),
        ),
        migrations.AddField(
            model_name='station',
            name='id_sohuu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Sở hữu (ID_SOHUU)'),
        ),
        migrations.AddField(
            model_name='station',
            name='id_tba',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID TBA (ID_TBA)'),
        ),
        migrations.AddField(
            model_name='station',
            name='id_tinh',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Tỉnh (ID_TINH)'),
        ),
        migrations.AddField(
            model_name='station',
            name='id_ttvh',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Trạng thái vận hành (ID_TTVH)'),
        ),
        migrations.AddField(
            model_name='station',
            name='id_vung',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Vùng (ID_VUNG)'),
        ),
        migrations.AddField(
            model_name='station',
            name='kieu_ht_dk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kiểu HT ĐK (KIEU_HT_DK)'),
        ),
        migrations.AddField(
            model_name='station',
            name='kieu_tram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kiểu trạm (KIEU_TRAM)'),
        ),
        migrations.AddField(
            model_name='station',
            name='loai_tram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Loại trạm (LOAI_TRAM)'),
        ),
        migrations.AddField(
            model_name='station',
            name='ngay_ld',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày lắp đặt (NGAY_LD)'),
        ),
        migrations.AddField(
            model_name='station',
            name='ngay_vh',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày vận hành (NGAY_VH)'),
        ),
        migrations.AddField(
            model_name='station',
            name='phuong',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phường (PHUONG)'),
        ),
        migrations.AddField(
            model_name='station',
            name='quan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Quận (QUAN)'),
        ),
        migrations.AddField(
            model_name='station',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sắp xếp (SAPXEP)'),
        ),
        migrations.AddField(
            model_name='station',
            name='tinh',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tỉnh (TINH)'),
        ),
        migrations.AddField(
            model_name='station',
            name='vung',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vùng (VUNG)'),
        ),
        migrations.AlterField(
            model_name='station',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Mã (MA)'),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_name',
            field=models.CharField(max_length=200, verbose_name='Tên (TEN)'),
        ),
    ]
