# Generated by Django 6.0.7 on 2026-07-28 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0007_alter_station_options_station_id_capda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bay',
            name='i_dm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='I_DM'),
        ),
        migrations.AddField(
            model_name='bay',
            name='id_capda',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Cấp điện áp (ID_CAPDA)'),
        ),
        migrations.AddField(
            model_name='bay',
            name='id_dvi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Đơn vị (ID_DVI)'),
        ),
        migrations.AddField(
            model_name='bay',
            name='id_nlo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Ngăn lộ (ID_NLO)'),
        ),
        migrations.AddField(
            model_name='bay',
            name='id_sohuu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Sở hữu (ID_SOHUU)'),
        ),
        migrations.AddField(
            model_name='bay',
            name='id_tba',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID TBA (ID_TBA)'),
        ),
        migrations.AddField(
            model_name='bay',
            name='id_ttvh',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Trạng thái vận hành (ID_TTVH)'),
        ),
        migrations.AddField(
            model_name='bay',
            name='ngay_vh',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày vận hành (NGAY_VH)'),
        ),
        migrations.AddField(
            model_name='bay',
            name='sdm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SDM'),
        ),
        migrations.AddField(
            model_name='bay',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sắp xếp (SAPXEP)'),
        ),
        migrations.AddField(
            model_name='bay',
            name='ten_tram',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên trạm (TEN_TRAM)'),
        ),
        migrations.AddField(
            model_name='bay',
            name='u_dm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='U_DM'),
        ),
        migrations.AlterField(
            model_name='bay',
            name='bay_code',
            field=models.CharField(max_length=50, verbose_name='Mã (MA)'),
        ),
        migrations.AlterField(
            model_name='bay',
            name='bay_name',
            field=models.CharField(max_length=100, verbose_name='Tên (TEN)'),
        ),
        migrations.AlterField(
            model_name='bay',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bays', to='stations.station'),
        ),
    ]
