# Generated by Django 6.0.7 on 2026-07-28 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0008_bay_i_dm_bay_id_capda_bay_id_dvi_bay_id_nlo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relay',
            name='id_capda',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Cấp điện áp (ID_CAPDA)'),
        ),
        migrations.AddField(
            model_name='relay',
            name='id_doituong',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Đối tượng (ID_DOITUONG)'),
        ),
        migrations.AddField(
            model_name='relay',
            name='id_dvi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Đơn vị (ID_DVI)'),
        ),
        migrations.AddField(
            model_name='relay',
            name='id_hang_sx',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Hãng sản xuất (ID_HANG_SX)'),
        ),
        migrations.AddField(
            model_name='relay',
            name='id_loai_dt',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Loại đối tượng (ID_LOAI_DT)'),
        ),
        migrations.AddField(
            model_name='relay',
            name='id_loai_tb',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Loại thiết bị (ID_LOAI_TB)'),
        ),
        migrations.AddField(
            model_name='relay',
            name='id_nuoc_sx',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Nước sản xuất (ID_NUOC_SX)'),
        ),
        migrations.AddField(
            model_name='relay',
            name='id_sohuu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Sở hữu (ID_SOHUU)'),
        ),
        migrations.AddField(
            model_name='relay',
            name='id_tbi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Thiết bị (ID_TBI)'),
        ),
        migrations.AddField(
            model_name='relay',
            name='id_ttvh',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Trạng thái vận hành (ID_TTVH)'),
        ),
        migrations.AddField(
            model_name='relay',
            name='id_vtri_dat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Vị trí đặt (ID_VTRI_DAT)'),
        ),
        migrations.AddField(
            model_name='relay',
            name='ngay_vh',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày vận hành (NGAY_VH)'),
        ),
        migrations.AddField(
            model_name='relay',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sắp xếp (SAPXEP)'),
        ),
        migrations.AlterField(
            model_name='relay',
            name='bay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relays', to='stations.bay'),
        ),
        migrations.AlterField(
            model_name='relay',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='relay',
            name='relay_code',
            field=models.CharField(max_length=50, verbose_name='Mã (MA)'),
        ),
        migrations.AlterField(
            model_name='relay',
            name='relay_name',
            field=models.CharField(max_length=100, verbose_name='Tên (TEN)'),
        ),
    ]
