# Generated by Django 6.0.7 on 2026-07-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0009_relay_id_capda_relay_id_doituong_relay_id_dvi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bay',
            name='bay_name',
            field=models.CharField(max_length=255, verbose_name='Tên (TEN)'),
        ),
        migrations.AlterField(
            model_name='bay',
            name='ten_tram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên trạm (TEN_TRAM)'),
        ),
        migrations.AlterField(
            model_name='relay',
            name='relay_name',
            field=models.CharField(max_length=255, verbose_name='Tên (TEN)'),
        ),
    ]
