# Generated by Django 6.0.7 on 2026-07-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0010_alter_bay_bay_name_alter_bay_ten_tram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bay',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='relay',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='station',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
