# Generated by Django 6.0.7 on 2026-07-18 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sheets', '0001_initial'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('actual_check_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='SCHEDULED', max_length=50)),
                ('relay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.relay')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.settingsheet')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodicCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_code', models.CharField(max_length=50)),
                ('measured_value', models.FloatField()),
                ('deviation_percent', models.FloatField()),
                ('is_within_tolerance', models.BooleanField()),
                ('periodic_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checks.periodiccheck')),
            ],
        ),
    ]
