# Generated by Django 6.0.7 on 2026-07-19 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0001_initial'),
        ('sheets', '0007_remove_settingsheet_assigned_supervisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodiccheck',
            name='sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheets.settingsheet'),
        ),
    ]
