"""Production document orchestration for relay-form OCR."""

from .orchestrator import (
    DocumentOcrOrchestrator,
    PdfCandidate,
    ProgressCallback,
    field_text,
    flatten_record,
    note_candidate,
    page_role,
)
from .observability import JsonLineFormatter, ProgressEvent, ServiceProgressCallback
from .schemas import (
    Artifact,
    ArtifactManifest,
    BusinessResult,
    Confidence,
    ConfidenceLabel,
    DocumentIdentity,
    ErrorCode,
    ErrorStage,
    ExtractedField,
    FieldResolutionStatus,
    NoteCandidate,
    OcrRequest,
    OcrResult,
    OcrWarning,
    Page1Fields,
    PageResult,
    PageRole,
    PageStatus,
    ProcessingStatus,
    PublicError,
    ReviewStatus,
    SettingRecord,
    StageTimings,
    Timing,
)
from .service import PIPELINE_VERSION, RelayFormOcrService
from .workspace import (
    CleanupPlan,
    WorkspaceCollisionError,
    WorkspaceHandle,
    WorkspaceManager,
    WorkspaceSecurityError,
    WorkspaceWriteError,
)

__all__ = [
    "DocumentOcrOrchestrator",
    "Artifact",
    "ArtifactManifest",
    "BusinessResult",
    "Confidence",
    "ConfidenceLabel",
    "DocumentIdentity",
    "ErrorCode",
    "ErrorStage",
    "ExtractedField",
    "FieldResolutionStatus",
    "NoteCandidate",
    "OcrRequest",
    "OcrResult",
    "OcrWarning",
    "Page1Fields",
    "PageResult",
    "PageRole",
    "PageStatus",
    "PdfCandidate",
    "PIPELINE_VERSION",
    "ProcessingStatus",
    "ProgressCallback",
    "ProgressEvent",
    "PublicError",
    "RelayFormOcrService",
    "ReviewStatus",
    "SettingRecord",
    "ServiceProgressCallback",
    "StageTimings",
    "Timing",
    "CleanupPlan",
    "WorkspaceCollisionError",
    "WorkspaceHandle",
    "WorkspaceManager",
    "WorkspaceSecurityError",
    "WorkspaceWriteError",
    "JsonLineFormatter",
    "field_text",
    "flatten_record",
    "note_candidate",
    "page_role",
]
