# Generated by Django 6.0.7 on 2026-07-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementunit',
            name='parent_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã đơn vị cha (MA_DONVI_CHA)'),
        ),
        migrations.AddField(
            model_name='managementunit',
            name='sort_order',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sắp xếp (SAPXEP)'),
        ),
        migrations.AddField(
            model_name='managementunit',
            name='unit_level',
            field=models.IntegerField(default=1, verbose_name='Cấp đơn vị (CAP_DONVI)'),
        ),
    ]
