# Generated by Django 6.0.7 on 2026-07-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_managementunit_parent_code_managementunit_sort_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingcountry',
            name='legacy_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã ID gốc (ID)'),
        ),
        migrations.AddField(
            model_name='manufacturingcountry',
            name='sort_order',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sắp xếp (SAPXEP)'),
        ),
    ]
