# Generated by Django 6.0.7 on 2026-07-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_manufacturingcountry_legacy_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='sort_order',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sắp xếp (SAPXEP)'),
        ),
    ]
