# Generated by Django 6.0.7 on 2026-07-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_ownership_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='voltagelevel',
            name='legacy_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã phụ (MA)'),
        ),
        migrations.AddField(
            model_name='voltagelevel',
            name='sort_order',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sắp xếp (SAPXEP)'),
        ),
    ]
