# Generated by Django 6.0.7 on 2026-07-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_voltagelevel_legacy_code_voltagelevel_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã')),
                ('name', models.CharField(max_length=255, verbose_name='Tên')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_tba', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID TBA (ID_TBA)')),
                ('id_tinh', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Tỉnh (ID_TINH)')),
                ('tinh', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tỉnh (TINH)')),
                ('id_quan', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Quận (ID_QUAN)')),
                ('quan', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quận (QUAN)')),
                ('id_phuong', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Phường (ID_PHUONG)')),
                ('phuong', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phường (PHUONG)')),
                ('id_capda', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Cấp điện áp (ID_CAPDA)')),
                ('id_ttvh', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Trạng thái vận hành (ID_TTVH)')),
                ('kieu_tram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kiểu trạm (KIEU_TRAM)')),
                ('id_kieu_tram', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Kiểu trạm (ID_KIEU_TRAM)')),
                ('loai_tram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Loại trạm (LOAI_TRAM)')),
                ('id_loai_tram', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Loại trạm (ID_LOAI_TRAM)')),
                ('ngay_vh', models.DateTimeField(blank=True, null=True, verbose_name='Ngày vận hành (NGAY_VH)')),
                ('ngay_ld', models.DateTimeField(blank=True, null=True, verbose_name='Ngày lắp đặt (NGAY_LD)')),
                ('id_dvi', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Đơn vị (ID_DVI)')),
                ('id_vung', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Vùng (ID_VUNG)')),
                ('vung', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vùng (VUNG)')),
                ('id_sohuu', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Sở hữu (ID_SOHUU)')),
                ('kieu_ht_dk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kiểu HT ĐK (KIEU_HT_DK)')),
                ('id_kieu_ht_dk', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Kiểu HT ĐK (ID_KIEU_HT_DK)')),
                ('sort_order', models.IntegerField(blank=True, null=True, verbose_name='Sắp xếp (SAPXEP)')),
            ],
            options={
                'verbose_name': 'Danh mục Trạm',
                'verbose_name_plural': 'Danh mục Trạm',
            },
        ),
    ]
