# Generated by Django 6.0.7 on 2026-07-28 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_station'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Station',
        ),
    ]
