# Generated by Django 6.0.7 on 2026-07-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_delete_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='da_tke',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Điện áp thiết kế (DA_TKE)'),
        ),
        migrations.AddField(
            model_name='line',
            name='dz_cha',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Đường dây cha (DZ_CHA)'),
        ),
        migrations.AddField(
            model_name='line',
            name='i_chophep',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dòng điện cho phép (I_CHOPHEP)'),
        ),
        migrations.AddField(
            model_name='line',
            name='id_capda',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Cấp điện áp (ID_CAPDA)'),
        ),
        migrations.AddField(
            model_name='line',
            name='id_da_tke',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Điện áp thiết kế (ID_DA_TKE)'),
        ),
        migrations.AddField(
            model_name='line',
            name='id_dvi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Đơn vị (ID_DVI)'),
        ),
        migrations.AddField(
            model_name='line',
            name='id_dz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Đường dây (ID_DZ)'),
        ),
        migrations.AddField(
            model_name='line',
            name='id_dz_cha',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Đường dây cha (ID_DZ_CHA)'),
        ),
        migrations.AddField(
            model_name='line',
            name='id_nlo_cap',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Ngăn lộ cấp (ID_NLO_CAP)'),
        ),
        migrations.AddField(
            model_name='line',
            name='id_nlo_nhan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Ngăn lộ nhận (ID_NLO_NHAN)'),
        ),
        migrations.AddField(
            model_name='line',
            name='id_sohuu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Sở hữu (ID_SOHUU)'),
        ),
        migrations.AddField(
            model_name='line',
            name='id_tba_cap',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID TBA cấp (ID_TBA_CAP)'),
        ),
        migrations.AddField(
            model_name='line',
            name='id_tba_nhan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID TBA nhận (ID_TBA_NHAN)'),
        ),
        migrations.AddField(
            model_name='line',
            name='id_ttvh',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Trạng thái vận hành (ID_TTVH)'),
        ),
        migrations.AddField(
            model_name='line',
            name='ngay_vh',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày vận hành (NGAY_VH)'),
        ),
        migrations.AddField(
            model_name='line',
            name='nlo_cap',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ngăn lộ cấp (NLO_CAP)'),
        ),
        migrations.AddField(
            model_name='line',
            name='nlo_nhan',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ngăn lộ nhận (NLO_NHAN)'),
        ),
        migrations.AddField(
            model_name='line',
            name='so_mach',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Số mạch (SO_MACH)'),
        ),
        migrations.AddField(
            model_name='line',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sắp xếp (SAPXEP)'),
        ),
        migrations.AddField(
            model_name='line',
            name='tba_cap',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='TBA cấp (TBA_CAP)'),
        ),
        migrations.AddField(
            model_name='line',
            name='tba_nhan',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='TBA nhận (TBA_NHAN)'),
        ),
        migrations.AddField(
            model_name='line',
            name='tong_cdai',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tổng chiều dài (TONG_CDAI)'),
        ),
    ]
