# Generated by Django 6.0.7 on 2026-07-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_line_da_tke_line_dz_cha_line_i_chophep_line_id_capda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='id_capda',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Cấp điện áp (ID_CAPDA)'),
        ),
        migrations.AddField(
            model_name='project',
            name='id_ct',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Công trình (ID_CT)'),
        ),
        migrations.AddField(
            model_name='project',
            name='id_dvi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Đơn vị (ID_DVI)'),
        ),
        migrations.AddField(
            model_name='project',
            name='id_sohuu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Sở hữu (ID_SOHUU)'),
        ),
        migrations.AddField(
            model_name='project',
            name='id_ttvh',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Trạng thái vận hành (ID_TTVH)'),
        ),
        migrations.AddField(
            model_name='project',
            name='ma_ct_cha',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã Công trình cha (MA_CT_CHA)'),
        ),
        migrations.AddField(
            model_name='project',
            name='nam_xd',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Năm xây dựng (NAM_XD)'),
        ),
        migrations.AddField(
            model_name='project',
            name='ngay_vh',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày vận hành (NGAY_VH)'),
        ),
        migrations.AddField(
            model_name='project',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sắp xếp (SAPXEP)'),
        ),
        migrations.AddField(
            model_name='project',
            name='ten_ct_cha',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên Công trình cha (TEN_CT_CHA)'),
        ),
    ]
