# Generated by Django 6.0.7 on 2026-07-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_project_id_capda_project_id_ct_project_id_dvi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='duong_vao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Đường vào (DUONG_VAO)'),
        ),
        migrations.AddField(
            model_name='location',
            name='hanh_lang',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hành lang (HANH_LANG)'),
        ),
        migrations.AddField(
            model_name='location',
            name='id_capda',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Cấp điện áp (ID_CAPDA)'),
        ),
        migrations.AddField(
            model_name='location',
            name='id_ct',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Công trình (ID_CT)'),
        ),
        migrations.AddField(
            model_name='location',
            name='id_dvi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Đơn vị (ID_DVI)'),
        ),
        migrations.AddField(
            model_name='location',
            name='id_khuvuc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Khu vực (ID_KHUVUC)'),
        ),
        migrations.AddField(
            model_name='location',
            name='id_sodo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Sơ đồ (ID_SODO)'),
        ),
        migrations.AddField(
            model_name='location',
            name='id_sohuu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Sở hữu (ID_SOHUU)'),
        ),
        migrations.AddField(
            model_name='location',
            name='id_ttvh',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Trạng thái vận hành (ID_TTVH)'),
        ),
        migrations.AddField(
            model_name='location',
            name='id_vitri',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Vị trí (ID_VITRI)'),
        ),
        migrations.AddField(
            model_name='location',
            name='khoang_cot',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Khoảng cột (KHOANG_COT)'),
        ),
        migrations.AddField(
            model_name='location',
            name='khoang_neo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Khoảng néo (KHOANG_NEO)'),
        ),
        migrations.AddField(
            model_name='location',
            name='khu_vuc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Khu vực (KHU_VUC)'),
        ),
        migrations.AddField(
            model_name='location',
            name='ngay_vh',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày vận hành (NGAY_VH)'),
        ),
        migrations.AddField(
            model_name='location',
            name='so_do',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sơ đồ (SO_DO)'),
        ),
        migrations.AddField(
            model_name='location',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sắp xếp (SAPXEP)'),
        ),
        migrations.AddField(
            model_name='location',
            name='ten_ct',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên Công trình (TEN_CT)'),
        ),
    ]
